### ISSUE TITLE
Bullet Force update broke the app

### ISSUE THREAD

**Issue by JackinSac** [holly-hacker/BulletForceHaxV2#12]
Whenever I run app.exe it gives me the error:
Could not find poki regex 1

![image](https://user-images.githubusercontent.com/87680958/219978910-e8044b10-78b8-4292-8ca4-6bde526e7aaa.png)

**Comment by JackinSac** [comment]
I also get the same error when running the first release

**Comment by JackinSac** [comment]
found where the error looks like it should come from in bulletforcehax2_lib/src/version_scraper.rs line 82 but it says could not find **CG** regex 1 instead of poki

**Comment by JackinSac** [comment]
This is probably relevant idk but when I try cargo run --release it give me this 
`
C:\Users\HP\Downloads\BulletForceHaxV2-main>cargo run --release
   Compiling proc-macro2 v1.0.47
   Compiling quote v1.0.21
   Compiling syn v1.0.103
   Compiling cfg-if v1.0.0
   Compiling log v0.4.17
error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

note: VS Code is a different product, and is not sufficient.

error: could not compile `quote` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `syn` due to previous error
error: could not compile `log` due to previous error
error: could not compile `proc-macro2` due to previous error

C:\Users\HP\Downloads\BulletForceHaxV2-main>pause
Press any key to continue . . .
`

**Comment by holly-hacker** [comment]
There have been changes to bullet force which cause other parts to break too. New reverse engineering efforts need to be made to bring BulletForceHaxV2 back up to date.

**Comment by JackinSac** [comment]
If there is any way I can help, just let me know. I know python, java, javascript, html, c#, and lua, but I am planning on learning c++ and rust soon so I might be able to help

**Comment by holly-hacker** [comment]
I've pushed some changes that update the scraping to the newest version but there's still an issue where the game loads infinitely on launch. I don't have time today to continue looking but feel free to have a look yourself.

**Comment by JackinSac** [comment]
I ran the file through an ai and it said this:
The issue with this code is that there is no timeout set for the HTTP request. If the request takes too long to get a response, the code will enter an infinite loop and the data will never be retrieved. To fix this, you can set a timeout for the request using the `timeout` parameter in the `Request::builder()` function.

**Comment by JackinSac** [comment]
Also idk if this is good code bc I don't know rust yet, but I let the ai generate some code and it returned this:
`//! Provides a method to download the latest version of the game files.

use std::time::{Duration, Instant};

use anyhow::{anyhow, Context, Result};
use hyper::{body::HttpBody, Body, Client, Request};
use tokio::sync::mpsc::{channel, Receiver, Sender};
use tower::{Service, ServiceBuilder, ServiceExt};
use tower_http::decompression::{Decompression, DecompressionLayer};
use tracing::debug;

const CG_FRAME_URL: &str = "https://games.crazygames.com/en_US/bullet-force-multiplayer/index.html";
const CG_JSON_PATTERN: &str = "(?m)^var options = (.+);$";

/// Describes the role of a downloading file.
#[derive(Clone, Copy)]
pub enum FileType {
    UnityLoader,
    Framework,
    Code,
    Data,
}

/// Indicates progress on a downloading file
pub enum ProgressReport {
    /// Indicates that a file is being downloaded and lists the download progress.
    Progress {
        file_type: FileType,
        name: String,
        downloaded: u64,
        total: Option<u64>,
    },
    /// Indicates that a file has finished downloading.
    FileDownloaded {
        file_type: FileType,
        name: String,
        data: Vec<u8>,
    },
    /// Indicates that all files have been downloaded and the download process has finished.
    AllFilesDownloaded,
    /// Indicates that something went wrong with the download and the download process has been aborted.
    Crashed(String),
}

/// Starts a thread that scrapes and downloads the game files. It returns a receiver that produces progress info.
pub fn start_download_thread() -> Result<Receiver<ProgressReport>> {
    let (tx, rx) = channel(128);

    tokio::spawn(async move {
        let tx = tx.clone();
        if let Err(e) = do_download(tx.clone()).await {
            tracing::error!("Error while downloading version: {e}");
            _ = tx.send(ProgressReport::Crashed(e.to_string())).await;
        }
    });

    Ok(rx)
}

async fn do_download(tx: Sender<ProgressReport>) -> Result<()> {
    let client = Client::builder().build::<_, hyper::Body>(hyper_tls::HttpsConnector::new());
    let mut client = ServiceBuilder::new()
        .layer(DecompressionLayer::new())
        .service(client);

    // find game files
    let frame_source = hyper_get(&mut client, CG_FRAME_URL)
        .await
        .context("get source_1")?;
    let json_match = regex::Regex::new(CG_JSON_PATTERN)?
        .captures(&frame_source)
        .ok_or_else(|| anyhow!("Could not find json regex"))?
        .get(1)
        .ok_or_else(|| anyhow!("Could not find group in json regex"))?;
    let json_string = json_match.as_str();
    let json_obj: serde_json::Value = serde_json::from_str(json_string)?;

    let loader_options = json_obj["loaderOptions"]
        .as_object()
        .context("get .loaderOptions")?;
    let config_options = loader_options["unityConfigOptions"]
        .as_object()
        .context("get .loaderOptions.unityConfigOptions")?;

    let url_loader = loader_options["unityLoaderUrl"]
        .as_str()
        .context("get .loaderOptions.unityLoaderUrl")?;
    let url_code = config_options["codeUrl"]
        .as_str()
        .context("get .loaderOptions.unityConfigOptions.codeUrl")?;
    let url_data = config_options["dataUrl"]
        .as_str()
        .context("get .loaderOptions.unityConfigOptions.dataUrl")?;
    let url_framework = config_options["frameworkUrl"]
        .as_str()
        .context("get .loaderOptions.unityConfigOptions.frameworkUrl")?;

    // TODO: can happen in parallel
    for (url, file_type) in [
        (url_loader, FileType::UnityLoader),
        (url_code, FileType::Code),
        (url_data, FileType::Data),
        (url_framework, FileType::Framework),
    ] {
        let file_name = url.split('/').last().unwrap();
        download_file_with_progress(&mut client, url, file_name, file_type, tx.clone()).await?;
    }

    tx.send(ProgressReport::AllFilesDownloaded)
        .await
        .context("send progress report")?;

    Ok(())
}

async fn download_file_with_progress(
    client: &mut Service<Request<Body>, Response = hyper::Response<Body>, Error = hyper::Error>,
    url: &str,
    file_name: &str,
    file_type: FileType,
    tx: Sender<ProgressReport>,
) -> Result<()> {
    let start_time = Instant::now();

    debug!("Starting download of {:?} {}", file_type, file_name);
    let mut response = hyper_get(client, url).await?;

    let mut total_bytes = 0;
    let mut downloaded_bytes = 0;
    let mut data = Vec::new();
    while let Some(chunk) = response.body_mut().data().await {
        let data_chunk = chunk?;
        total_bytes += data_chunk.len() as u64;
        downloaded_bytes += data_chunk.len() as u64;
        data.extend_from_slice(&data_chunk);
        _ = tx.send(ProgressReport::Progress {
            file_type,
            name: file_name.to_string(),
            downloaded: downloaded_bytes,
            total: Some(total_bytes),
        })
        .await;
    }

    let duration = start_time.elapsed();
    debug!(
        "Finished download of {:?} {}, took {}s",
        file_type,
        file_name,
        duration.as_secs_f64()
    );

    _ = tx
        .send(ProgressReport::FileDownloaded {
            file_type,
            name: file_name.to_string(),
            data,
        })
        .await;

    Ok(())
}

async fn hyper_get(
    client: &mut Service<Request<Body>, Response = hyper::Response<Body>, Error = hyper::Error>,
    url: &str,
) -> Result<String> {
    let uri = url.parse::<hyper::Uri>()?;
    let request = Request::builder()
        .uri(uri)
        .header("Cache-Control", "no-cache")
        .body(Body::empty())
        .context("build http request")?;

    let mut response = client.call(request).await.context("http call")?;
    let mut body_data = Vec::new();
    while let Some(chunk) = response.body_mut().data().await {
        let data = chunk?;
        body_data.extend_from_slice(&data);
    }
    let body = String::from_utf8(body_data).context("parse http body")?;

    Ok(body)
}`

**Comment by holly-hacker** [comment]
The version scraper works fine. The current issue is related to HTTP proxying. If you want to temporarily bypass it, disable the http hook by removing [this if block](https://github.com/holly-hacker/BulletForceHaxV2/blob/1b0c6fd882e7892ec3e3f4421d00e958d0819946/bulletforcehax2_app/assets/index.html#L64).

**Comment by JackinSac** [comment]
Also everytime i try building the project it goes good until it tries to build bulletforcehaxv2_app and then it gives me this error:
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
and then a shit ton of paths to a ton of .rcgu.o files, and then at the end it also says:
note: ld: cannot find -lntdll
but i cant find anything on lntdll anywhere

**Comment by JackinSac** [comment]
I did that and the app works fine except for freezing sometimes after switching windows

**Comment by holly-hacker** [comment]
The current `main` version has HTTP proxying disable by default. #13 tracks this now.
